### ISSUE TITLE
Missing mineable tags

### ISSUE THREAD

**Issue by KateYagi** [Autovw/MoreConcrete#1]
I was building a concrete house, and I needed to move my staircase by one block, but I noticed that it was taking a long time to mine and wasn't dropping anything. Looking at the jar, the loot tables are correct, so I looked at the jar for Create, and they have a json in data/ minecraft/ tags/ blocks/ **mineable** called pickaxe.json that includes all blocks breakable with a pickaxe. Adding the following to that json fixed the issue.
`
{
  "replace": false,
  "values": [
    "#moreconcrete:walls",
    "#moreconcrete:stairs",
    "#moreconcrete:slabs",
    "#moreconcrete:pressure_plates",
    "#moreconcrete:levers",
    "#moreconcrete:fences",
    "#moreconcrete:fence_gates"
  ]
}
`
I wasn't quite sure how to make a push request for this, sorry. I'm still new to github.

**Comment by Autovw** [comment]
Thanks for your report!
The initial version of this mod was created on version 1.16.5 while the mineable tag system got introduced in 1.17, and I must've forgotten to add the tag during the porting process. Easy fix on my end, will release a patch for both 1.17.1 and 1.18.1 ASAP.
