### ISSUE TITLE
Add new language DE/German

### ISSUE THREAD

**Issue by DancerVlt69** [Autovw/MoreConcrete#3]
here I have a German translation for your mod:

`{
  "block.moreconcrete.white_concrete_slab": "Weiße Betonstufe",
  "block.moreconcrete.orange_concrete_slab": "Orangene Betonstufe",
  "block.moreconcrete.magenta_concrete_slab": "Magenta Betonstufe",
  "block.moreconcrete.light_blue_concrete_slab": "Hellblaue Betonstufe",
  "block.moreconcrete.yellow_concrete_slab": "Gelbe Betonstufe",
  "block.moreconcrete.lime_concrete_slab": "Hellgrüne Betonstufe",
  "block.moreconcrete.pink_concrete_slab": "Rosa Betonstufe",
  "block.moreconcrete.gray_concrete_slab": "Graue Betonstufe",
  "block.moreconcrete.light_gray_concrete_slab": "Hellgraue Betonstufe",
  "block.moreconcrete.cyan_concrete_slab": "Türkise Betonstufe",
  "block.moreconcrete.purple_concrete_slab": "Lila Betonstufe",
  "block.moreconcrete.blue_concrete_slab": "Blaue Betonstufe",
  "block.moreconcrete.brown_concrete_slab": "Braune Betonstufe",
  "block.moreconcrete.green_concrete_slab": "Grüne Betonstufe",
  "block.moreconcrete.red_concrete_slab": "Rote Betonstufe",
  "block.moreconcrete.black_concrete_slab": "Schwarze Betonstufe",

  "block.moreconcrete.white_concrete_stairs": "Weiße Betontreppe",
  "block.moreconcrete.orange_concrete_stairs": "Orangene Betontreppe",
  "block.moreconcrete.magenta_concrete_stairs": "Magenta Betontreppe",
  "block.moreconcrete.light_blue_concrete_stairs": "Hellblaue Betontreppe",
  "block.moreconcrete.yellow_concrete_stairs": "Gelbe Betontreppe",
  "block.moreconcrete.lime_concrete_stairs": "Hellgrüne Betontreppe",
  "block.moreconcrete.pink_concrete_stairs": "Rosa Betontreppe",
  "block.moreconcrete.gray_concrete_stairs": "Graue Betontreppe",
  "block.moreconcrete.light_gray_concrete_stairs": "Hellgraue Betontreppe",
  "block.moreconcrete.cyan_concrete_stairs": "Türkise Betontreppe",
  "block.moreconcrete.purple_concrete_stairs": "Lila Betontreppe",
  "block.moreconcrete.blue_concrete_stairs": "Blaue Betontreppe",
  "block.moreconcrete.brown_concrete_stairs": "Braune Betontreppe",
  "block.moreconcrete.green_concrete_stairs": "Grüne Betontreppe",
  "block.moreconcrete.red_concrete_stairs": "Rote Betontreppe",
  "block.moreconcrete.black_concrete_stairs": "Schwarze Betontreppe",

  "block.moreconcrete.white_concrete_wall": "Weiße Betonmauer",
  "block.moreconcrete.orange_concrete_wall": "Orangene Betonmauer",
  "block.moreconcrete.magenta_concrete_wall": "Magenta Betonmauer",
  "block.moreconcrete.light_blue_concrete_wall": "Hellblaue Betonmauer",
  "block.moreconcrete.yellow_concrete_wall": "Gelbe Betonmauer",
  "block.moreconcrete.lime_concrete_wall": "Hellgrüne Betonmauer",
  "block.moreconcrete.pink_concrete_wall": "Rosa Betonmauer",
  "block.moreconcrete.gray_concrete_wall": "Graue Betonmauer",
  "block.moreconcrete.light_gray_concrete_wall": "Hellgraue Betonmauer",
  "block.moreconcrete.cyan_concrete_wall": "Türkise Betonmauer",
  "block.moreconcrete.purple_concrete_wall": "Lila Betonmauer",
  "block.moreconcrete.blue_concrete_wall": "Blaue Betonmauer",
  "block.moreconcrete.brown_concrete_wall": "Braune Betonmauer",
  "block.moreconcrete.green_concrete_wall": "Grüne Betonmauer",
  "block.moreconcrete.red_concrete_wall": "Rote Betonmauer",
  "block.moreconcrete.black_concrete_wall": "Schwarze Betonmauer",

  "block.moreconcrete.white_concrete_lever": "Weißer Betonhebel",
  "block.moreconcrete.orange_concrete_lever": "Orangener Betonhebel",
  "block.moreconcrete.magenta_concrete_lever": "Magenta Betonhebel",
  "block.moreconcrete.light_blue_concrete_lever": "Hellblauer Betonhebel",
  "block.moreconcrete.yellow_concrete_lever": "Gelber Betonhebel",
  "block.moreconcrete.lime_concrete_lever": "Hellgrüner Betonhebel",
  "block.moreconcrete.pink_concrete_lever": "Rosa Betonhebel",
  "block.moreconcrete.gray_concrete_lever": "Grauer Betonhebel",
  "block.moreconcrete.light_gray_concrete_lever": "Hellgrauer Betonhebel",
  "block.moreconcrete.cyan_concrete_lever": "Türkiser Betonhebel",
  "block.moreconcrete.purple_concrete_lever": "Lila Betonhebel",
  "block.moreconcrete.blue_concrete_lever": "Blauer Betonhebel",
  "block.moreconcrete.brown_concrete_lever": "Brauner Betonhebel",
  "block.moreconcrete.green_concrete_lever": "Grüner Betonhebel",
  "block.moreconcrete.red_concrete_lever": "Roter Betonhebel",
  "block.moreconcrete.black_concrete_lever": "Schwarzer Betonhebel",

  "block.moreconcrete.white_concrete_pressure_plate": "Weiße Betondruckplatte",
  "block.moreconcrete.orange_concrete_pressure_plate": "Orangene Betondruckplatte",
  "block.moreconcrete.magenta_concrete_pressure_plate": "Magenta Betondruckplatte",
  "block.moreconcrete.light_blue_concrete_pressure_plate": "Hellblaue Betondruckplatte",
  "block.moreconcrete.yellow_concrete_pressure_plate": "Gelbe Betondruckplatte",
  "block.moreconcrete.lime_concrete_pressure_plate": "Hellgrüne Betondruckplatte",
  "block.moreconcrete.pink_concrete_pressure_plate": "Rosa Betondruckplatte",
  "block.moreconcrete.gray_concrete_pressure_plate": "Graue Betondruckplatte",
  "block.moreconcrete.light_gray_concrete_pressure_plate": "Hellgraue Betondruckplatte",
  "block.moreconcrete.cyan_concrete_pressure_plate": "Türkise Betondruckplatte",
  "block.moreconcrete.purple_concrete_pressure_plate": "Lila Betondruckplatte",
  "block.moreconcrete.blue_concrete_pressure_plate": "Blaue Betondruckplatte",
  "block.moreconcrete.brown_concrete_pressure_plate": "Braune Betondruckplatte",
  "block.moreconcrete.green_concrete_pressure_plate": "Grüne Betondruckplatte",
  "block.moreconcrete.red_concrete_pressure_plate": "Rote Betondruckplatte",
  "block.moreconcrete.black_concrete_pressure_plate": "Schwarze Betondruckplatte",

  "block.moreconcrete.white_concrete_fence": "Weißer Betonzaun",
  "block.moreconcrete.orange_concrete_fence": "Orangener Betonzaun",
  "block.moreconcrete.magenta_concrete_fence": "Magenta Betonzaun",
  "block.moreconcrete.light_blue_concrete_fence": "Hellblauer Betonzaun",
  "block.moreconcrete.yellow_concrete_fence": "Gelber Betonzaun",
  "block.moreconcrete.lime_concrete_fence": "Hellgrüner Betonzaun",
  "block.moreconcrete.pink_concrete_fence": "Rosa Betonzaun",
  "block.moreconcrete.gray_concrete_fence": "Grauer Betonzaun",
  "block.moreconcrete.light_gray_concrete_fence": "Hellgrauer Betonzaun",
  "block.moreconcrete.cyan_concrete_fence": "Türkiser Betonzaun",
  "block.moreconcrete.purple_concrete_fence": "Lila Betonzaun",
  "block.moreconcrete.blue_concrete_fence": "Blauer Betonzaun",
  "block.moreconcrete.brown_concrete_fence": "Brauner Betonzaun",
  "block.moreconcrete.green_concrete_fence": "Grüner Betonzaun",
  "block.moreconcrete.red_concrete_fence": "Roter Betonzaun",
  "block.moreconcrete.black_concrete_fence": "Schwarzer Betonzaun",

  "block.moreconcrete.white_concrete_fence_gate": "Weißes Betonzauntor",
  "block.moreconcrete.orange_concrete_fence_gate": "Orangenes Betonzauntor",
  "block.moreconcrete.magenta_concrete_fence_gate": "Magenta Betonzauntor",
  "block.moreconcrete.light_blue_concrete_fence_gate": "Hellblaues Betonzauntor",
  "block.moreconcrete.yellow_concrete_fence_gate": "Gelbes Betonzauntor",
  "block.moreconcrete.lime_concrete_fence_gate": "Hellgrünes Betonzauntor",
  "block.moreconcrete.pink_concrete_fence_gate": "Rosa Betonzauntor",
  "block.moreconcrete.gray_concrete_fence_gate": "Graues Betonzauntor",
  "block.moreconcrete.light_gray_concrete_fence_gate": "Hellgraues Betonzauntor",
  "block.moreconcrete.cyan_concrete_fence_gate": "Türkises Betonzauntor",
  "block.moreconcrete.purple_concrete_fence_gate": "Lila Betonzauntor",
  "block.moreconcrete.blue_concrete_fence_gate": "Blaues Betonzauntor",
  "block.moreconcrete.brown_concrete_fence_gate": "Braunes Betonzauntor",
  "block.moreconcrete.green_concrete_fence_gate": "Grünes Betonzauntor",
  "block.moreconcrete.red_concrete_fence_gate": "Rotes Betonzauntor",
  "block.moreconcrete.black_concrete_fence_gate": "Schwarzes Betonzauntor",

  "block.moreconcrete.white_concrete_button": "Weißer Betonknopf",
  "block.moreconcrete.orange_concrete_button": "Orangener Betonknopf",
  "block.moreconcrete.magenta_concrete_button": "Magenta Betonknopf",
  "block.moreconcrete.light_blue_concrete_button": "Hellblauer Betonknopf",
  "block.moreconcrete.yellow_concrete_button": "Gelber Betonknopf",
  "block.moreconcrete.lime_concrete_button": "Hellgrüner Betonknopf",
  "block.moreconcrete.pink_concrete_button": "Rosa Betonknopf",
  "block.moreconcrete.gray_concrete_button": "Grauer Betonknopf",
  "block.moreconcrete.light_gray_concrete_button": "Hellgrauer Betonknopf",
  "block.moreconcrete.cyan_concrete_button": "Türkiser Betonknopf",
  "block.moreconcrete.purple_concrete_button": "Lila Betonknopf",
  "block.moreconcrete.blue_concrete_button": "Blauer Betonknopf",
  "block.moreconcrete.brown_concrete_button": "Brauner Betonknopf",
  "block.moreconcrete.green_concrete_button": "Grüner Betonknopf",
  "block.moreconcrete.red_concrete_button": "Roter Betonknopf",
  "block.moreconcrete.black_concrete_button": "Schwarzer Betonknopf"`

best regards

**Comment by DancerVlt69** [comment]
![image](https://user-images.githubusercontent.com/49952690/169677288-431cfdb1-9d6f-4954-8592-e8ae5ad5203e.png)

On the test - in single play - it looks like, the translation works. But btw. with my Texture-Pack "Chroma Hills" the lever looks verrrry scarrrry. In 'Vanilla' all is fine.

**Comment by Autovw** [comment]
Forgot to close this, but I've added the translation during the 1.19 update of the mod :)
